version: "3.7"

services:            
    client:
        build:
            context: ./client
        image: client:latest
        environment:
            CHOKIDAR_USEPOLLING: "true"
            REACT_APP_BACKEND_URL: http://localhost:53294
        volumes:
            - "./client:/app"
            - "/app/node_modules"
        ports:
            - "3001:3000"
        tty: true