version: "3.7"

services:            
    client:
        build:
            context: ./client
        image: client:latest
        environment:
            CHOKIDAR_USEPOLLING: "true"
            REACT_APP_BACKEND_URL: http://localhost:4000
        volumes:
            - "./client:/app"
            - "/app/node_modules"
        ports:
            - "3001:3000"
        tty: true
        
    server:
        build:
            context: ./server
        image: server:latest
        ports:
            - "4000:80"

    client-test:
        build:
            context: ./client
            dockerfile: Dockerfile.test
        volumes:
            - "./client:/app"
            - "/app/node_modules"
        command: "npm test"